name: Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Don't forget to update `Cargo.toml`
      - name: Setup rust 1.89.0
        run: rustup toolchain install 1.89.0 --profile minimal --no-self-update
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --verbose
